### ISSUE TITLE
Relay info from risc0 isn't easily findable from this repo

### ISSUE THREAD

**Issue by pdg744** [risc0/bonsai-foundry-template#43]
Users who navigate to `relays` folder right now find no readme. On the other hand, the readme on `risc0` is super rich with information: https://github.com/risc0/risc0/tree/main/bonsai/ethereum-relay

Is the info there applicable here?

**Comment by pdg744** [comment]
(will revisit this once #29 lands)

**Comment by pdg744** [comment]
OK #29 has landed; adding a README to the `relay` folder that points to and/or duplicates the content [here](https://github.com/risc0/risc0/tree/main/bonsai/ethereum-relay) would be helpful.

**Comment by tzerrell** [comment]
@mothran is the `risc0`-repo relay information appropriate for this repo's `relays` folder? Who would be a good person to put together a README for this?

**Comment by pdg744** [comment]
Migrating from DevEx board to Bonsai board; feel free to close if it doesn't feel necessary.

**Comment by pdg744** [comment]
Resolved!
