### ISSUE TITLE
Reproducible builds sometimes get bypassed

### ISSUE THREAD

**Issue by capossele** [risc0/bonsai-foundry-template#88]
In the Governance example of the `risc0` repo, specifically on this branch:  cardosaum/refactor-governance-example-new-foundry-template, the same instructions that work within the foundry template (e.g., `RISC0_USE_DOCKER=1 cargo build`) do not work, resulting in the build being built bypassing Docker.

**Comment by flaub** [comment]
Can you add the error message and more context for this?

**Comment by capossele** [comment]
Totally, I've just created the issue to track it down. I'll update its description

**Comment by nategraf** [comment]
We have not been able to reproduce this issue recently. Closing this issue, and will reopen if this is seen again.
